[CRJS206][team5R] Add rule CRJS206 - Avoid using high accuracy geolocation
green-code-initiative/ecoCode-linter pull request #10
Opened 2023-04-06 13:23 UTC by Houssainatou

2023-04-07 09:56 UTC, utarwyn requested changes

2023-04-07 09:56 UTC, utarwyn commented on eslint-plugin/lib/rules/avoid-high-accuracy-geolocation.js
> +        "'{{notAllowedValue}}' is not a valid value, should be false.",
Could you use a more precise message here?
It will be used in the SonarQube interface when a warning will be reported

2023-04-07 09:56 UTC, utarwyn commented on .yarnrc.yml
> +yarnPath: .yarn/releases/yarn-3.4.1.cjs
Why was the last line deleted?

2023-04-07 09:56 UTC, utarwyn commented on eslint-plugin/lib/rules/avoid-high-accuracy-geolocation.js
> +            data: { notAllowedValue: true },
The data is a constant "true", so I think it is not necessary to pass it to the message

2023-04-07 09:56 UTC, utarwyn commented on yarn.lock
The build does not seem to pass due to modification on this lockfile, can you verify?

2023-04-07 09:56 UTC, utarwyn commented on eslint-plugin/docs/rules/avoid-high-accuracy-geolocation.md
> +Examples of **incorrect** code for this rule:
As requested in another PR, I think we can use "non compliant"/"compliant" in this file, instead of "incorrect"/"correct"

2023-04-07 10:00 UTC, utarwyn commented
Thank you for your work, this rule is really relevant :pray:

Can you run script `update:eslint-docs` and command `yarn version check -i` to automatically update all documentation files with this new rule, as described in [CONTRIBUTING.md](https://github.com/green-code-initiative/ecoCode-linter/blob/main/eslint-plugin/CONTRIBUTING.md)?

2023-04-07 11:44 UTC, Silicoman commented
@Chmaqo, @Houssainatou , as we internally discuss yesterday about issues packaging, can you inform us if you can do  corrections ?
Just to know, if i have to do this. Thanks for your time :)

2023-04-26 17:41 UTC, utarwyn commented
Did you have time to consider my comments?

2023-04-26 19:40 UTC, Houssainatou commented
> Did you have time to consider my comments?

@Chmaqo can you check this request please ?
Thanks

2023-05-07 21:33 UTC, dedece35 requested changes
Hi @Houssainatou,

please, could you : 
- take into account review notes
- resolve conflicts / build problems
- add some test in js-test-project repository
- modify `CHANGELOG.md` file
- modify `RULES.md` file with your rule

... in ordre to merge this PR.

2023-05-14 16:52 UTC, utarwyn approved these changes
Hello, I have worked on the feedback myself to integrate this rule in the next release of the plugin. Thanks for your work! :100:

If you have other ideas or concerns, the collective is always open to contributions!

2023-05-14 16:56 UTC, utarwyn approved these changes

2023-05-14 16:57 UTC, merged